name: Setup CRD with Fluxbox on Ubuntu

on:
  workflow_dispatch:

jobs:
  setup-remote:
    runs-on: ubuntu-latest

    steps:
    - name: Install Fluxbox, Xterm, and CRD
      run: |
        sudo apt update 
        sudo apt upgrade -y
        sudo apt install -y fluxbox xterm wget curl python3 

        # Download and install Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt -f install -y

   
    - name: Authenticate CRD
      run: |
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AVMBsJhFNCnOtsrATi44FTBcQW6SJxQwH_XtXUr06Uj061XdI8tWtktK5BTs_A1aGVpAtQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --pin=111111
    - name: sleep
      run: |
       sleep 200000000
